/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as PublicServicesRouteImport } from './routes/_public.services'
import { Route as PublicPortfolioRouteImport } from './routes/_public.portfolio'
import { Route as PublicContactRouteImport } from './routes/_public.contact'
import { Route as PublicCompanyRouteImport } from './routes/_public.company'
import { Route as PublicCareersRouteImport } from './routes/_public.careers'
import { Route as PublicBlogRouteImport } from './routes/_public.blog'
import { Route as PublicBlogSlugRouteImport } from './routes/_public.blog.$slug'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicServicesRoute = PublicServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPortfolioRoute = PublicPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCompanyRoute = PublicCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCareersRoute = PublicCareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBlogRoute = PublicBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBlogSlugRoute = PublicBlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PublicBlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/blog': typeof PublicBlogRouteWithChildren
  '/careers': typeof PublicCareersRoute
  '/company': typeof PublicCompanyRoute
  '/contact': typeof PublicContactRoute
  '/portfolio': typeof PublicPortfolioRoute
  '/services': typeof PublicServicesRoute
  '/blog/$slug': typeof PublicBlogSlugRoute
}
export interface FileRoutesByTo {
  '/blog': typeof PublicBlogRouteWithChildren
  '/careers': typeof PublicCareersRoute
  '/company': typeof PublicCompanyRoute
  '/contact': typeof PublicContactRoute
  '/portfolio': typeof PublicPortfolioRoute
  '/services': typeof PublicServicesRoute
  '/': typeof PublicIndexRoute
  '/blog/$slug': typeof PublicBlogSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/_public/blog': typeof PublicBlogRouteWithChildren
  '/_public/careers': typeof PublicCareersRoute
  '/_public/company': typeof PublicCompanyRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/portfolio': typeof PublicPortfolioRoute
  '/_public/services': typeof PublicServicesRoute
  '/_public/': typeof PublicIndexRoute
  '/_public/blog/$slug': typeof PublicBlogSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/careers'
    | '/company'
    | '/contact'
    | '/portfolio'
    | '/services'
    | '/blog/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/blog'
    | '/careers'
    | '/company'
    | '/contact'
    | '/portfolio'
    | '/services'
    | '/'
    | '/blog/$slug'
  id:
    | '__root__'
    | '/_public'
    | '/_public/blog'
    | '/_public/careers'
    | '/_public/company'
    | '/_public/contact'
    | '/_public/portfolio'
    | '/_public/services'
    | '/_public/'
    | '/_public/blog/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/services': {
      id: '/_public/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof PublicServicesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/portfolio': {
      id: '/_public/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PublicPortfolioRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/company': {
      id: '/_public/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof PublicCompanyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/careers': {
      id: '/_public/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof PublicCareersRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/blog': {
      id: '/_public/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof PublicBlogRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/blog/$slug': {
      id: '/_public/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof PublicBlogSlugRouteImport
      parentRoute: typeof PublicBlogRoute
    }
  }
}

interface PublicBlogRouteChildren {
  PublicBlogSlugRoute: typeof PublicBlogSlugRoute
}

const PublicBlogRouteChildren: PublicBlogRouteChildren = {
  PublicBlogSlugRoute: PublicBlogSlugRoute,
}

const PublicBlogRouteWithChildren = PublicBlogRoute._addFileChildren(
  PublicBlogRouteChildren,
)

interface PublicRouteChildren {
  PublicBlogRoute: typeof PublicBlogRouteWithChildren
  PublicCareersRoute: typeof PublicCareersRoute
  PublicCompanyRoute: typeof PublicCompanyRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicPortfolioRoute: typeof PublicPortfolioRoute
  PublicServicesRoute: typeof PublicServicesRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicBlogRoute: PublicBlogRouteWithChildren,
  PublicCareersRoute: PublicCareersRoute,
  PublicCompanyRoute: PublicCompanyRoute,
  PublicContactRoute: PublicContactRoute,
  PublicPortfolioRoute: PublicPortfolioRoute,
  PublicServicesRoute: PublicServicesRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
